### PR TITLE
Use getColumnModel().getColumnsBy for get column

### PR DESCRIPTION
**Pull request by kandy**
In my case Ext.each by config don't work

### CODE REVIEW

**Comment by nene** [comment]
Hello kandy,

Could you provide an example code that demonstrates how the current implementation fails.

When I look at the source of ColumnModel.getColumnsBy() then I see that it accesses the same  ColumnModel.config property - and yet you say that accessing the .config property fails for you. I find it hard to believe that your suggested fix makes any difference at all.

**Comment by kandy** [comment]
See https://github.com/kandy/filter-row/blob/sample1/test/test.html

**Comment by nene** [comment]
This clone() method you are using is not a good way to clone/copy an array. It does something more like subclassing this specific array, which I don't think you intended, plus subclassing Array doesn't work well in JavaScript.

The result of this is that `Ext.isArray(clone([1,2,3]))` will return false. Basically rendering this array unusable for ExtJS in many-many cases. Although this "array" works with getColumnsBy(), it's simply a coincidence of how getColumnsBy() is implemented.

I suggest you use a better method for copying arrays. For example:

```
function copyArray(a) {
  var b = [];
  for (var i=0, len=a.length; i<len; i++) {
    b.push(a[i]);
  }
  return b;
}
```

**Comment by kandy** [comment]
You right.
clone([]) instanceof Array return true, but clone([]).toString() throwing error

**Pull request closed without merging**
